name: snakemake
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aioeasywebdav=2.4.0=py36h9f0ad1d_1001
  - aiohttp=3.7.3=py36h8f6f2f9_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - attrs=20.3.0=pyhd3deb0d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bcrypt=3.2.0=py36h8c4c3a4_1
  - boto3=1.16.37=pyhd8ed1ab_0
  - botocore=1.19.38=pyhd8ed1ab_0
  - brotlipy=0.7.0=py36he6145b8_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2020.12.5=py36h5fab9bb_0
  - cffi=1.14.4=py36hc120d54_1
  - chardet=3.0.4=py36h9880bd3_1008
  - coincbc=2.10.5=hcee13e7_1
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cryptography=3.3.1=py36h0a59100_0
  - datrie=0.8.2=py36h8c4c3a4_1
  - decorator=4.4.2=py_0
  - docutils=0.16=py36h5fab9bb_2
  - dropbox=10.9.0=pyhd3deb0d_0
  - expat=2.2.9=he1b5a44_2
  - fftw=3.3.8=nompi_h8cb7ab2_1114
  - filechunkio=1.6=py36_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h7e3eb15_1002
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h7ca028e_0
  - fribidi=1.0.10=h36c2ea0_0
  - ftputil=3.2=py36_0
  - gdk-pixbuf=2.42.2=h19a9c64_1
  - gettext=0.19.8.1=h0b5b191_1005
  - ghostscript=9.18=1
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.5=py_0
  - gitpython=3.1.11=py_0
  - glib=2.66.3=h9c3ff4c_1
  - google-api-core=1.22.2=py36h9f0ad1d_0
  - google-api-python-client=1.12.8=pyhd3deb0d_0
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-auth-httplib2=0.0.4=pyh9f0ad1d_0
  - google-cloud-core=1.5.0=pyhd3deb0d_0
  - google-cloud-storage=1.19.0=py_0
  - google-crc32c=1.1.0=py36h0208b43_0
  - google-resumable-media=1.2.0=pyhd3deb0d_0
  - googleapis-common-protos=1.52.0=py36h5fab9bb_1
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.42.3=h0511662_0
  - grpcio=1.34.0=py36h8e87921_0
  - harfbuzz=2.7.2=ha5b49bf_1
  - httplib2=0.18.1=pyh9f0ad1d_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - idna_ssl=1.1.0=py36h9f0ad1d_1001
  - imagemagick=7.0.10_28=pl5262hd815ba0_2
  - importlib-metadata=3.3.0=py36h5fab9bb_2
  - importlib_metadata=3.3.0=hd8ed1ab_2
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h516909a_2002
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=py_2
  - jupyter_core=4.7.0=py36h5fab9bb_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_1
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libcrc32c=1.1.1=he1b5a44_2
  - libffi=3.3=h58526e2_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libglib=2.66.3=h1f3bc88_1
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=3_openblas
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.14.0=h780b84a_0
  - librsvg=2.50.2=h3442318_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h4f3a223_6
  - libtool=2.4.6=h58526e2_1007
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.1.0=h76fa15c_4
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=1.1.1=py36he6145b8_2
  - multidict=5.1.0=py36h8f6f2f9_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.5=py_0
  - numpy=1.19.4=py36h2aa4a07_2
  - oauth2client=1.5.2=py36_0
  - openjpeg=2.3.1=hf7af979_3
  - openssl=1.1.1i=h7f98852_0
  - pandas=1.1.5=py36h284efc9_0
  - pango=1.42.4=h69149e4_5
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h36c2ea0_1008
  - pip=20.3.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - prettytable=2.0.0=pyhd8ed1ab_0
  - protobuf=3.14.0=py36hc4f0c31_0
  - psutil=5.7.3=py36he6145b8_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.3.1=py36h9f0ad1d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.3=pyhd8ed1ab_0
  - pygraphviz=1.6=py36hf2b72a0_1
  - pynacl=1.4.0=py36h8c4c3a4_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py36h1d69622_1
  - pysftp=0.2.9=py36_0
  - pysocks=1.7.1=py36h9880bd3_2
  - python=3.6.12=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.4=pyhd8ed1ab_0
  - pyyaml=5.3.1=py36he6145b8_1
  - ratelimiter=1.2.0=py_1002
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - rsa=3.1.4=py36_0
  - s3transfer=0.3.3=pyhd8ed1ab_5
  - setuptools=49.6.0=py36h9880bd3_2
  - simplejson=3.8.1=py36_0
  - six=1.15.0=pyh9f0ad1d_0
  - slacker=0.14.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake=5.30.2=0
  - snakemake-minimal=5.30.2=py_0
  - sqlite=3.34.0=h74cdb3f_0
  - star=2.7.6a=0
  - tk=8.6.10=h21135ba_1
  - toposort=1.5=py_3
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.2=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py36h1d69622_2
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py36h8f6f2f9_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
prefix: /public/home/zhangzhiyang/anaconda3/envs/snakemake
